extends:
  - 'plugin:@typescript-eslint/recommended'
  - '@redhat-cloud-services/eslint-config-redhat-cloud-services'

parser: '@typescript-eslint/parser'
globals:
  insights: 'readonly'
rules:
  react/prop-types: 'off'
